services:
  db:
    image: postgres:17
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 20
    networks:
      - mspr

  rabbitmq:
    image: rabbitmq:3-management
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: app
      RABBITMQ_DEFAULT_PASS: app
      RABBITMQ_DEFAULT_VHOST: /
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 5s
      timeout: 5s
      retries: 30
    networks:
      - mspr

  api-product:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    restart: unless-stopped
    env_file: .env
    environment:
      # --- DB ---
      DATABASE_URL: ${DATABASE_URL}

      # --- Keycloak ---
      KEYCLOAK_ISSUER: ${KEYCLOAK_ISSUER:-http://host.docker.internal:8081/realms/paye-ton-kawa}
      KEYCLOAK_JWKS_URL: ${KEYCLOAK_JWKS_URL:-http://host.docker.internal:8081/realms/paye-ton-kawa/protocol/openid-connect/certs}
      ROLE_READ: ${ROLE_READ:-product:read}
      ROLE_WRITE: ${ROLE_WRITE:-product:write}

      # --- RabbitMQ ---
      # Astuce: encode le vhost "/" en %2F pour éviter les surprises
      RABBITMQ_URL: ${RABBITMQ_URL:-amqp://app:app@rabbitmq:5672/%2F}
      RABBITMQ_EXCHANGE: ${RABBITMQ_EXCHANGE:-products}
      RABBITMQ_EXCHANGE_TYPE: ${RABBITMQ_EXCHANGE_TYPE:-fanout}

      # --- Métadonnées app (optionnel) ---
      APP_TITLE: ${APP_TITLE:-Product API - PayeTonKawa}
      APP_VERSION: ${APP_VERSION:-1.0.0}
      APP_DESCRIPTION: ${APP_DESCRIPTION:-API Produits CRUD}

      # --- Logging ---
      LOG_DIR: /app/logs
      LOG_FILE: app.log
      LOG_ACCESS_FILE: access.log
      LOG_LEVEL: ${LOG_LEVEL:-INFO}
      LOG_FORMAT: ${LOG_FORMAT:-json}
      LOG_MAX_BYTES: ${LOG_MAX_BYTES:-10485760}
      LOG_BACKUP_COUNT: ${LOG_BACKUP_COUNT:-5}
      LOG_ENABLE_CONSOLE: ${LOG_ENABLE_CONSOLE:-true}
      REQUEST_ID_HEADER: ${REQUEST_ID_HEADER:-X-Request-ID}

    volumes:
      - .:/app
      - logs:/app/logs
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - mspr

volumes:
  postgres_data:
  logs:

networks:
  mspr:
    driver: bridge