[tool.pytest.ini_options]
addopts = "-q --cov=app --cov-report=xml:coverage.xml --cov-report=term-missing --cov-branch"
testpaths = ["tests"]
asyncio_mode = "auto"

[tool.coverage.run]
branch = true
source = ["app"]
omit = [
  "app/__init__.py",
  "app/api/__init__.py",
  "app/api/v1/__init__.py",
  "app/main.py",
  "**/__init__.py",
]

[tool.ruff]
output-format = "json"
select = ["E", "F", "I", "UP", "B"]
fix = false

[tool.mypy]
python_version = "3.12"
ignore_missing_imports = true
pretty = true
strict = false
plugins = ["pydantic.mypy"]
